language: python
python:
  - "2.6"
  - "2.7"
# pypy-dev package.
  - "pypy"
# command to install dependencies
install: "pip install -r requirements/base.txt"
# command to run tests
script: python pro_tips/manage.py test --settings=settings.test
